### ISSUE TITLE
issues getting it to work..

### ISSUE THREAD

**Issue by Zeldocto** [fuyuneko/startpage#6]
I downloaded the master.zip file and dragged it into my c drive just like I would do with any other startpage, but it doesnt work for me. I have it set up like this https://puu.sh/rjgbL/431092054c.png

When I open the index file all I get is a white blank page.

**Comment by fuyuneko** [comment]
What browser are you using and what version? Tested it with Firefox 48.0.2, 49.0 and Chromium 53.0 and works fine for me. Could you post the console output of the page?
Also make sure NoScript or something similar isn't blocking anything.

**Comment by Zeldocto** [comment]
Im using Google Chrome and the newest/latest version. Here is the console output https://puu.sh/rjIYy/a366bdbd27.png

**Comment by fuyuneko** [comment]
You'll need to install the startpage as a extension because it loads it's configuration from a file which isn't allowed for normal pages in Chrome.
This isn't mentioned in the current readme but I'm writing a [new one](https://github.com/fuyuneko/startpage/blob/readme/README.md) which explains how to install it:
> To use the startpage in Chromium and Chrome you'll have to use it as an extension. Just download the .crx file from the [latest release ](https://github.com/fuyuneko/startpage/releases/download/v1.5.0/startpage.crx)and open it with Chrome.
If a .crx file for a release isn't available or you want to use the latest version on github you will have to [download](https://github.com/fuyuneko/startpage/blob/chromium-patch/manifest.json) the manifest.json for the startpage and save it in the same directory as the startpage. Go to Chrome's extension menu, enable developer mode, click on "load unpacked extension" and select the folder you saved the startage in.
